In [1]:
"""Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.
"""
import numpy as np
def gen_vandermonde_mat(onedarray,no_col,increasing=False):
    if not increasing:
        vander_mat = np.array([x**i for x in onedarray for i in range(no_col)]).reshape(onedarray.size,no_col)
    elif increasing:
        vander_mat = np.array([x**(no_col-1-i) for x in onedarray for i in range(no_col)]).reshape(onedarray.size,no_col)

    return vander_mat

arr = np.array([1,2,3,4,6,8,10])
no_col = 7

matrix = gen_vandermonde_mat(arr,no_col,True)

print("Vandermonde Ouptput Matrix is: \n",gen_vandermonde_mat(arr,no_col,True))
print("\nVandermonde Ouptput Matrix is: \n",gen_vandermonde_mat(arr,no_col,False))
matrix
np.linalg.det(matrix)

Vandermonde Ouptput Matrix is: 
 [[      1       1       1       1       1       1       1]
 [     64      32      16       8       4       2       1]
 [    729     243      81      27       9       3       1]
 [   4096    1024     256      64      16       4       1]
 [  46656    7776    1296     216      36       6       1]
 [ 262144   32768    4096     512      64       8       1]
 [1000000  100000   10000    1000     100      10       1]]

Vandermonde Ouptput Matrix is: 
 [[      1       1       1       1       1       1       1]
 [      1       2       4       8      16      32      64]
 [      1       3       9      27      81     243     729]
 [      1       4      16      64     256    1024    4096]
 [      1       6      36     216    1296    7776   46656]
 [      1       8      64     512    4096   32768  262144]
 [      1      10     100    1000   10000  100000 1000000]]


-58525286399.99711

In [2]:
"""Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values."""
import numpy as np
def moving_average(a, k=1) :
    mov_avg = np.cumsum(a, dtype=float)
    mov_avg[k:] = mov_avg[k:] - mov_avg[:-k]
    return mov_avg[k - 1:] / k

a = [10,20,30,40,50,60,70,80,90,100]
print(moving_average(a, k=4))

print("-"*50)

b = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(b, k=3))


[25. 35. 45. 55. 65. 75. 85.]
--------------------------------------------------
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
